name: PR
on:
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION_PATH: BananaGit/BananaGit.sln
      PROJECT_PATH: BananaGit/BananaGit/BananaGit.csproj
      DEPLOY_PATH: builds/BananaGit/
      
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_TEST_TOKEN }}
        persist-credentials: true
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore 
      
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
      env: 
        GIT_TEST_TOKEN: ${{ secrets.GIT_TEST_TOKEN }}
        GIT_TEST_USERNAME: ${{ secrets.GIT_TEST_USERNAME }}
        GIT_TEST_EMAIL: ${{ secrets.GIT_TEST_EMAIL }}
